<?xml version="1.0"?>
<!DOCTYPE purse [
<!ELEMENT purse (coin*)>
<!ELEMENT coin (value, name)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name lang CDATA "en">
]>
<purse>
    <coin>
        <value>0.5</value>
        <name lang="en">half dollar</name>
    </coin>
    <coin>
        <value>0.25</value>
        <name lang="en">quarter</name>
    </coin>
</purse>
